services:
  fuseki:
    image: stain/jena-fuseki:latest
    container_name: f1-fuseki
    ports:
      - "3030:3030"
    environment:
      - ADMIN_PASSWORD=${FUSEKI_ADMIN_PASSWORD}
      - FUSEKI_ARGS=--cors
    volumes:
      - ./fuseki-data:/fuseki
